version: 2

models:
  - name: stock_indicators
    description: "Final output table containing all stock indicators"
    columns:
      - name: symbol_date_key
        description: "Primary key combining symbol and date"
        tests:
          - unique
          - not_null
      - name: symbol
        description: "Stock symbol"
      - name: close
        description: "Closing price"
      - name: ma_5
        description: "5-day moving average"
      - name: ma_20
        description: "20-day moving average"
      - name: trend
        description: "Current trend (uptrend/downtrend/sideways)"
      - name: avg_gain
        description: "Average gain for RSI calculation"
      - name: avg_loss
        description: "Average loss for RSI calculation"
      - name: rsi
        description: "Relative Strength Index"
      - name: daily_price_return
        description: "Daily price return percentage" 