name: 'customer_churn'
version: '1.0.0'
config-version: 2

profile: 'customer_churn'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  customer_churn:
    materialized: table
    schema: public
    staging:
      materialized: view
    marts:
      materialized: table 