version: '3'
services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
    volumes:
      - ./superset_home:/app/superset_home
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  postgres:
    image: postgres:13
    container_name: superset_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
    volumes:
      - superset-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "superset"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset-init:
    image: apache/superset:latest
    container_name: superset_init
    depends_on:
      - postgres
      - superset
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin
        --username admin
        --firstname Superset
        --lastname Admin
        --email admin@superset.com
        --password admin &&
      superset init"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset

volumes:
  superset-postgres: 