build_mau:
  outputs:
    dev:
      account: sfedu02-ksb65579
      database: USER_DB_MACKEREL
      password: 
      role: TRAINING_ROLE
      schema: ANALYTICS
      threads: 1
      type: snowflake
      user: MACKEREL
      warehouse: MACKEREL_QUERY_WH
  target: dev
